#! /bin/bash

sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
timedatectl --no-ask-password set-timezone America/Sao_Paul
timedatectl --no-ask-password set-ntp 1
localectl --no-ask-password set-locale LANG="en_US.UTF-8" LC_TIME="en_US.UTF-8"

# Set keymaps
localectl --no-ask-password set-keymap br-abnt2

#Add parallel downloading
sed -i 's/^#Para/Para/' /etc/pacman.conf


sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
pacman -Sy --noconfirm

PKGS=(
    'mesa'
    'xorg'
    'xorg-server'
    'xorg-apps'
    'xorg-drivers'
    'xorg-xkill'
    'xorg-xinit'
    'binutils'
    'dosfstools'
    'linux-headers'
    'noto-fonts-emoji'
    'usbutils'
    'xdg-user-dirs'
    'alsa-plugins'
    'alsa-utils'
    'autoconf'
    'automake'
    'awesome-terminal-fonts'
    'bash-completion'
    'bind'
    'bison'
    'bluez'
    'bluez-libs'
    'bluez-utils'
    'btrfs-progs'
    'celluloid'
    ' cmatrix'
    'cronie'
    'dialog'
    'dmidecode'
    'dnsmasq'
    'dtc'
    'efibootmgr'
    'egl-wayland'
    'exfat-utils'
    'flex'
    'fuse2'
    'fuse3'
    'fuseiso'
    'gamemode'
    'gcc'
    'grub-customizer'
    'gst-libav'
    'gst-plugins-good'
    'gst-plugins-ugly'
    'haveged'
    'htop'
    'kitty'
    'libdvdcss'
    'libtool'
    'lsof'
    'lzop'
    'm4'
    'make'
    'neofetch'
    'ntfs-3g'
    'ntp'
    'networkmanager'
    'openbsd-netcat'
    'openssh'
    'os-prober'
    'p7zip'
    'papirus-icon-theme'
    'patch'
    'picom'
    'pkgconf'
    'powerline-fonts'
    'pipewire'
    'lib32-pipewire'
    'pipewire-alsa'
    'pipewire-pulse'
    'pipewire-jack'
    'lib32-pipewire-jack'
    'pipewire-media-session'
    'python-notify2'
    'python-psutil'
    'python-pyqt5'
    'python-pip'
    'qemu'
    'snap-pac'
    'snapper'
    'swtpm'
    'synergy'
    'terminus-font'
    'traceroute'
    'ufw'
    'unrar'
    'unzip'
    'virt-manager'
    'virt-viewer'
    'which'
    'zip'
    'zsh'
    'zsh-syntax-highlighting'
    'zsh-autosuggestions'
    'htop'
    'reflector'
    'rsync'
)

pacman -S "$PKGS" --noconfirm --needed
